### ISSUE TITLE
Syntax error when trying to setup Cluster

### ISSUE THREAD

**Issue by uplg** [cbrgm/ansible-pi3cluster-playbooks#8]
When trying to setup the cluster, following your tutorial  

$ ansible-playbook setup.yml --extra-vars "hosts=cluster" -u pirate --ask-pass --ask-become-pass
SSH password: 
SUDO password[defaults to SSH password]: 
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/root/ansible-pi3cluster-playbooks/setup.yml': line 10, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - basic
    when: hosts is defined
    ^ here

Can't do anything else

**Comment by cbrgm** [comment]
Hey sorry for my late reply! It seems there is an indent error, i will check that and fix it asap!

**Comment by moritz31** [comment]
- { role:basic, when: hosts is defined }
- { role:reboot, when: hosts is defined }

solved the problem for me :)
